name = "fpm-search"
version = "0.12.1"
license = "ISC"
author = "fpm-search contributors"
maintainer = "brocolis@eml.cc"
copyright = "2021 fpm-search contributors"

[dependencies]
fhash        = {git = "https://github.com/LKedward/fhash", rev = "125ac80a3e736c08ba46184150923baca09a6bfd" }
M_CLI2       = {git = "https://github.com/urbanjost/M_CLI2", rev = "54cd522b7e2a4a1d873580e4a2c56e34549a1182" }
M_strings    = {git = "https://github.com/urbanjost/M_strings"}
stdlib       = {git = "https://github.com/LKedward/stdlib-fpm.git"}
json-fortran = {git = "https://github.com/brocolis/json-fortran", rev = "0c0d36f0280e81524561b44b3e6467e003a363ef" }
M_match      = {git = "https://github.com/urbanjost/M_match.git" }
dynload-pcre = {git = "https://github.com/brocolis/dynload-pcre.git" }

[library]
source-dir="src"

[[executable]]
name="fpm-search"
source-dir="app"
main="main.f90"
