name = "avpkg"
version = "0.2.0"
license = "license"
author = "Une"
maintainer = "brocolis@eml.cc"
copyright = "2020 Jane Doe"

[dependencies]
fortran-curl = { git = "https://github.com/interkosmos/fortran-curl" }
M_strings = { git = "https://github.com/urbanjost/M_strings.git" }
fhash = {git="https://github.com/LKedward/fhash", tag="v0.1.0"}

[[executable]]
name="avpkg"
source-dir="app"
main="main.f90"

