name = "avpkg"
version = "0.6.0"
license = "ISC"
author = "avpkg contributors"
maintainer = "brocolis@eml.cc"
copyright = "2021 avpkg contributors"

[build]
link = ["json-c"]

[dependencies]
fortran-curl = {git = "https://github.com/interkosmos/fortran-curl" }
fortran-pcre = {git = "https://github.com/brocolis/fortran-pcre"}
fhash        = {git = "https://github.com/LKedward/fhash"}
M_CLI2       = {git = "https://github.com/urbanjost/M_CLI2" }

[library]
source-dir="src"

[[executable]]
name="avpkg"
source-dir="app"
main="main.f90"
