name = "avpkg"
version = "0.4.0"
license = "ISC"
author = "Carlos Une"
maintainer = "brocolis@eml.cc"
copyright = "2021 Carlos Une"

[build]
link = ["json-c"]

[dependencies]
fortran-curl = {git = "https://github.com/interkosmos/fortran-curl" }
fortran-pcre = {git = "https://github.com/brocolis/fortran-pcre"}
fhash        = {git = "https://github.com/LKedward/fhash"}

[library]
source-dir="src"

[[executable]]
name="avpkg"
source-dir="app"
main="main.f90"
