name = "fpm-search"
version = "0.13.0"
license = "ISC"
author = "fpm-search contributors"
maintainer = "brocolis@eml.cc"
copyright = "2021 fpm-search contributors"

[dependencies]
fhash        = {git = "https://github.com/LKedward/fhash", rev = "125ac80a3e736c08ba46184150923baca09a6bfd" }
M_CLI2       = {git = "https://github.com/urbanjost/M_CLI2", rev = "54cd522b7e2a4a1d873580e4a2c56e34549a1182" }
M_strings    = {git = "https://github.com/urbanjost/M_strings"}
stdlib       = {git = "https://github.com/LKedward/stdlib-fpm.git"}
json-fortran = {git = "https://github.com/jacobwilliams/json-fortran.git"}
M_match      = {git = "https://github.com/urbanjost/M_match.git" }
dynload-pcre = {git = "https://github.com/brocolis/dynload-pcre.git" }
M_escape     = {git = "https://github.com/urbanjost/M_escape.git", rev = "a32ece6a8cb355d2560c4478d17d6d51e8a0bba9" }

[library]
source-dir="src"

[[executable]]
name="fpm-search"
source-dir="app"
main="main.f90"
