name: fpm

on: [push, pull_request]

jobs:
  gfortran:
    runs-on: windows-latest

    env:
      FC: gfortran
      GCC_V: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Install fpm
      uses: fortran-lang/setup-fpm@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: |
        gfortran --version
        fpm build

    - name: Search
      run: |
        gfortran --version
        fpm run -- -V
